apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: buildkitd
  name: buildkitd
  namespace: build
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: buildkitd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: buildkitd
    spec:
      containers:
      - args:
        - --addr
        - unix:///run/user/1000/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:1234
        - --oci-worker-snapshotter
        - overlayfs
        image: moby/buildkit:master
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - buildctl
            - --addr
            - tcp://0.0.0.0:1234
            - debug
            - workers
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: buildkitd
        ports:
        - containerPort: 1234
          hostPort: 1234
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - buildctl
            - --addr
            - tcp://0.0.0.0:1234
            - debug
            - workers
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: "2"
            memory: 4Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30