apiVersion: v1
kind: ConfigMap
data:
  config.json: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "BASE64_AUTH"
        }
      }
    }
metadata:
  name: docker-config
  namespace: build
