// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: builder/pbs/recordpb/recordview.proto

package recordpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Giturl   string `protobuf:"bytes,2,opt,name=giturl,proto3" json:"giturl,omitempty"`
	Revision string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Image    string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Tag      string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *CreateRecordReq) Reset() {
	*x = CreateRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordReq) ProtoMessage() {}

func (x *CreateRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordReq.ProtoReflect.Descriptor instead.
func (*CreateRecordReq) Descriptor() ([]byte, []int) {
	return file_builder_pbs_recordpb_recordview_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRecordReq) GetGiturl() string {
	if x != nil {
		return x.Giturl
	}
	return ""
}

func (x *CreateRecordReq) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *CreateRecordReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateRecordReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type CreateRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string                            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *CreateRecordResp_RecordContainer `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateRecordResp) Reset() {
	*x = CreateRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResp) ProtoMessage() {}

func (x *CreateRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResp.ProtoReflect.Descriptor instead.
func (*CreateRecordResp) Descriptor() ([]byte, []int) {
	return file_builder_pbs_recordpb_recordview_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRecordResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateRecordResp) GetData() *CreateRecordResp_RecordContainer {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListRecordReq) Reset() {
	*x = ListRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordReq) ProtoMessage() {}

func (x *ListRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordReq.ProtoReflect.Descriptor instead.
func (*ListRecordReq) Descriptor() ([]byte, []int) {
	return file_builder_pbs_recordpb_recordview_proto_rawDescGZIP(), []int{2}
}

func (x *ListRecordReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListRecordReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string                          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *ListRecordResp_RecordContainer `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ListRecordResp) Reset() {
	*x = ListRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordResp) ProtoMessage() {}

func (x *ListRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordResp.ProtoReflect.Descriptor instead.
func (*ListRecordResp) Descriptor() ([]byte, []int) {
	return file_builder_pbs_recordpb_recordview_proto_rawDescGZIP(), []int{3}
}

func (x *ListRecordResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListRecordResp) GetData() *ListRecordResp_RecordContainer {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateRecordResp_RecordContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *CreateRecordResp_RecordContainer) Reset() {
	*x = CreateRecordResp_RecordContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecordResp_RecordContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResp_RecordContainer) ProtoMessage() {}

func (x *CreateRecordResp_RecordContainer) ProtoReflect() protoreflect.Message {
	mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResp_RecordContainer.ProtoReflect.Descriptor instead.
func (*CreateRecordResp_RecordContainer) Descriptor() ([]byte, []int) {
	return file_builder_pbs_recordpb_recordview_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateRecordResp_RecordContainer) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListRecordResp_RecordContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *ListRecordResp_RecordContainer) Reset() {
	*x = ListRecordResp_RecordContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordResp_RecordContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordResp_RecordContainer) ProtoMessage() {}

func (x *ListRecordResp_RecordContainer) ProtoReflect() protoreflect.Message {
	mi := &file_builder_pbs_recordpb_recordview_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordResp_RecordContainer.ProtoReflect.Descriptor instead.
func (*ListRecordResp_RecordContainer) Descriptor() ([]byte, []int) {
	return file_builder_pbs_recordpb_recordview_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListRecordResp_RecordContainer) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_builder_pbs_recordpb_recordview_proto protoreflect.FileDescriptor

var file_builder_pbs_recordpb_recordview_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x76, 0x69, 0x65,
	0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70,
	0x62, 0x1a, 0x21, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x69, 0x74, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x69, 0x74, 0x75, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x22, 0xa5, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3e,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b,
	0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x3b, 0x0a, 0x0d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x3d, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x16,
	0x5a, 0x14, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_builder_pbs_recordpb_recordview_proto_rawDescOnce sync.Once
	file_builder_pbs_recordpb_recordview_proto_rawDescData = file_builder_pbs_recordpb_recordview_proto_rawDesc
)

func file_builder_pbs_recordpb_recordview_proto_rawDescGZIP() []byte {
	file_builder_pbs_recordpb_recordview_proto_rawDescOnce.Do(func() {
		file_builder_pbs_recordpb_recordview_proto_rawDescData = protoimpl.X.CompressGZIP(file_builder_pbs_recordpb_recordview_proto_rawDescData)
	})
	return file_builder_pbs_recordpb_recordview_proto_rawDescData
}

var file_builder_pbs_recordpb_recordview_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_builder_pbs_recordpb_recordview_proto_goTypes = []interface{}{
	(*CreateRecordReq)(nil),                  // 0: recordpb.CreateRecordReq
	(*CreateRecordResp)(nil),                 // 1: recordpb.CreateRecordResp
	(*ListRecordReq)(nil),                    // 2: recordpb.ListRecordReq
	(*ListRecordResp)(nil),                   // 3: recordpb.ListRecordResp
	(*CreateRecordResp_RecordContainer)(nil), // 4: recordpb.CreateRecordResp.RecordContainer
	(*ListRecordResp_RecordContainer)(nil),   // 5: recordpb.ListRecordResp.RecordContainer
	(*Record)(nil),                           // 6: recordpb.Record
}
var file_builder_pbs_recordpb_recordview_proto_depIdxs = []int32{
	4, // 0: recordpb.CreateRecordResp.data:type_name -> recordpb.CreateRecordResp.RecordContainer
	5, // 1: recordpb.ListRecordResp.data:type_name -> recordpb.ListRecordResp.RecordContainer
	6, // 2: recordpb.CreateRecordResp.RecordContainer.record:type_name -> recordpb.Record
	6, // 3: recordpb.ListRecordResp.RecordContainer.records:type_name -> recordpb.Record
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_builder_pbs_recordpb_recordview_proto_init() }
func file_builder_pbs_recordpb_recordview_proto_init() {
	if File_builder_pbs_recordpb_recordview_proto != nil {
		return
	}
	file_builder_pbs_recordpb_record_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_builder_pbs_recordpb_recordview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_builder_pbs_recordpb_recordview_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_builder_pbs_recordpb_recordview_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_builder_pbs_recordpb_recordview_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_builder_pbs_recordpb_recordview_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecordResp_RecordContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_builder_pbs_recordpb_recordview_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecordResp_RecordContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_builder_pbs_recordpb_recordview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_builder_pbs_recordpb_recordview_proto_goTypes,
		DependencyIndexes: file_builder_pbs_recordpb_recordview_proto_depIdxs,
		MessageInfos:      file_builder_pbs_recordpb_recordview_proto_msgTypes,
	}.Build()
	File_builder_pbs_recordpb_recordview_proto = out.File
	file_builder_pbs_recordpb_recordview_proto_rawDesc = nil
	file_builder_pbs_recordpb_recordview_proto_goTypes = nil
	file_builder_pbs_recordpb_recordview_proto_depIdxs = nil
}
